### ISSUE TITLE
AI生图消息合成失败

### ISSUE THREAD

**Issue by ttk886** [CCLMSY/nonebot-plugin-sparkapi#9]
### Self-check

- [X] 我已明确我的问题
- [X] 我已阅读本项目及NoneBot2文档中的相关内容
- [X] 我已翻阅其他issue，并找不到相关问题

### 操作系统

windows10

### Python 版本

3.10.11

### 问题描述

已经开通相关AI生图权限，但生图不能输出。报错为：
 File "\python\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=35000, data={}, message='消息 合成失败，请查看日志或者检查输入。', echo='3')
后台查看文件夹images中也有相应的图片。

### 问题复现

配置了SPARKAPI_FL_IMGGEN = True，打开了生图配置

### 期望行为

期望大佬指导，查明错误原因。

### 截图或日志

Image Generation: Got Request, Generating...
Image Generation: OK!
Time Consumed: 11.31s
SparkApi\private_1017026528\images\20240724_135814.png
07-24 13:58:15 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_sparkapi.matchers.imggen, lineno=22) running complete
07-24 13:58:15 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_sparkapi.matchers.imggen, lineno=22) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "E:\python\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "E:\python\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "E:\python\lib\site-packages\uvicorn\main.py", line 587, in run
    server.run()
  File "E:\python\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "E:\python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "E:\python\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "E:\python\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "E:\python\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "E:\python\lib\asyncio\base_events.py", line 1909, in _run_once
    handle._run()
  File "E:\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\python\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "E:\python\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "E:\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "E:\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "E:\python\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "E:\python\lib\site-packages\nonebot_plugin_sparkapi\matchers\imggen.py", line 40, in _
    await mathcer_imggen.finish(MS.image(img))
  File "E:\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 582, in finish
    await cls.send(message, **kwargs)
  File "E:\python\lib\site-packages\nonebot\internal\matcher\matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "E:\python\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 225, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "E:\python\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 178, in send
    return await bot.send_msg(**params)
  File "E:\python\lib\site-packages\nonebot\internal\adapter\bot.py", line 122, in call_api
    raise exception
  File "E:\python\lib\site-packages\nonebot\internal\adapter\bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "E:\python\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 144, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "E:\python\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=35000, data={}, message='消息 合成失败，请查看日志或者检查输入。', echo='3')

**Comment by CCLMSY** [comment]
你好，本地测试没有出现这个问题

根据你提供的错误信息，猜测是 onebotV11适配器未成功处理图片并发送。

建议检查onebotv11适配器版本以及客户端适配器版本。

如果你仍在使用gocq-http，建议更换成其他客户端适配器。

**Comment by CCLMSY** [comment]
如果问题仍然存在，欢迎继续联系

**Comment by ttk886** [comment]
感谢回复，我这边继续自查一下

**Comment by CCLMSY** [comment]
由于你长时间未更新，就先关闭issue了，有其他情况欢迎继续反馈//
